/*
 * Copyright (C) 2021 rifqi
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package alingeo.matriks.ui;

import javax.swing.JFileChooser;
import java.io.File;
import java.util.Locale;

import alingeo.matriks.Matrix;
import alingeo.matriks.io.Parser;
import alingeo.matriks.solver.SPLSolver;
import alingeo.matriks.solver.SPLSolver.SolutionResult;
import alingeo.matriks.solver.DeterminantSolver;
import alingeo.matriks.solver.InversSolver;

/**
 *
 * @author rifqi
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.ButtonGroup();
        FileOpener = new javax.swing.JFileChooser();
        FileSaver = new javax.swing.JFileChooser();
        SidePanel = new javax.swing.JPanel();
        SideHeader = new javax.swing.JPanel();
        HeaderLabel = new javax.swing.JLabel();
        SideMenu = new javax.swing.JPanel();
        SPLLabel = new javax.swing.JLabel();
        SPLGauss = new javax.swing.JRadioButton();
        SPLGaussJordan = new javax.swing.JRadioButton();
        SPLMatriksBalikan = new javax.swing.JRadioButton();
        SPLCrammer = new javax.swing.JRadioButton();
        DeterminanLabel = new javax.swing.JLabel();
        DeterminanKofaktor = new javax.swing.JRadioButton();
        DeterminanOBE = new javax.swing.JRadioButton();
        InversLabel = new javax.swing.JLabel();
        InversGauss = new javax.swing.JRadioButton();
        InversAdjoin = new javax.swing.JRadioButton();
        ProblemSolverLabel = new javax.swing.JLabel();
        Interpolasi = new javax.swing.JRadioButton();
        Regresi = new javax.swing.JRadioButton();
        ExitButton = new javax.swing.JButton();
        LayeredPanel = new javax.swing.JLayeredPane();
        SPLGaussPanel = new javax.swing.JPanel();
        SPLGaussTitle = new javax.swing.JLabel();
        SPLGaussInst1 = new javax.swing.JLabel();
        SPLGaussInst2 = new javax.swing.JLabel();
        SPLGaussInst3 = new javax.swing.JLabel();
        SPLGaussInst4 = new javax.swing.JLabel();
        SPLGaussInst5 = new javax.swing.JLabel();
        SPLGaussInst6 = new javax.swing.JLabel();
        SPLGaussCalculate = new javax.swing.JButton();
        SPLGaussOpenFile = new javax.swing.JButton();
        SPLGaussFilepath = new javax.swing.JTextField();
        SPLGaussSave = new javax.swing.JButton();
        SPLGaussPrompt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SPLGaussInput = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        SPLGaussIntermediate = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        SPLGaussOutput = new javax.swing.JTextPane();
        SPLGaussJordanPanel = new javax.swing.JPanel();
        SPLGaussTitle4 = new javax.swing.JLabel();
        SPLGaussInst25 = new javax.swing.JLabel();
        SPLGaussInst26 = new javax.swing.JLabel();
        SPLGaussInst27 = new javax.swing.JLabel();
        SPLGaussInst28 = new javax.swing.JLabel();
        SPLGaussInst29 = new javax.swing.JLabel();
        SPLGaussInst30 = new javax.swing.JLabel();
        SPLGaussJordanCalculate = new javax.swing.JButton();
        SPLGaussJordanOpenFile = new javax.swing.JButton();
        SPLGaussJordanFilepath = new javax.swing.JTextField();
        SPLGaussJordanSave = new javax.swing.JButton();
        SPLGaussJordanPrompt = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        SPLGaussJordanInput = new javax.swing.JTextPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        SPLGaussJordanIntermediate = new javax.swing.JTextPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        SPLGaussJordanOutput = new javax.swing.JTextPane();
        DeterminanKofaktorPanel = new javax.swing.JPanel();
        DeterminanKofaktorTitle = new javax.swing.JLabel();
        SPLGaussInst7 = new javax.swing.JLabel();
        SPLGaussInst8 = new javax.swing.JLabel();
        SPLGaussInst9 = new javax.swing.JLabel();
        SPLGaussInst11 = new javax.swing.JLabel();
        DeterminanKofaktorCalculate = new javax.swing.JButton();
        DeterminanKofaktorOpenFile = new javax.swing.JButton();
        DeterminanKofaktorFilepath = new javax.swing.JTextField();
        DeterminanKofaktorSave = new javax.swing.JButton();
        DeterminanKofaktorPrompt = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        DeterminanKofaktorInput = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        DeterminanKofaktorOutput = new javax.swing.JTextPane();
        DeterminanOBEPanel = new javax.swing.JPanel();
        SPLGaussTitle1 = new javax.swing.JLabel();
        SPLGaussInst10 = new javax.swing.JLabel();
        SPLGaussInst12 = new javax.swing.JLabel();
        SPLGaussInst13 = new javax.swing.JLabel();
        SPLGaussInst14 = new javax.swing.JLabel();
        SPLGaussInst15 = new javax.swing.JLabel();
        DeterminanOBECalculate = new javax.swing.JButton();
        DeterminanOBEOpenFile = new javax.swing.JButton();
        DeterminanOBEFilepath = new javax.swing.JTextField();
        DeterminanOBESave = new javax.swing.JButton();
        DeterminanOBEPrompt = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        DeterminanOBEInput = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        DeterminanOBEIntermediate = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        DeterminanOBEOutput = new javax.swing.JTextPane();
        InversGaussPanel = new javax.swing.JPanel();
        SPLGaussTitle2 = new javax.swing.JLabel();
        SPLGaussInst16 = new javax.swing.JLabel();
        SPLGaussInst17 = new javax.swing.JLabel();
        SPLGaussInst18 = new javax.swing.JLabel();
        SPLGaussInst20 = new javax.swing.JLabel();
        InversGaussCalculate = new javax.swing.JButton();
        InversGaussOpenFile = new javax.swing.JButton();
        InversGaussFilepath = new javax.swing.JTextField();
        InversGaussSave = new javax.swing.JButton();
        InversGaussPrompt = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        InversGaussInput = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        InversGaussOutput = new javax.swing.JTextPane();
        InversAdjoinPanel = new javax.swing.JPanel();
        SPLGaussTitle3 = new javax.swing.JLabel();
        SPLGaussInst19 = new javax.swing.JLabel();
        SPLGaussInst21 = new javax.swing.JLabel();
        SPLGaussInst22 = new javax.swing.JLabel();
        SPLGaussInst23 = new javax.swing.JLabel();
        SPLGaussInst24 = new javax.swing.JLabel();
        InversAdjoinCalculate = new javax.swing.JButton();
        InversAdjoinOpenFile = new javax.swing.JButton();
        InversAdjoinFilepath = new javax.swing.JTextField();
        InversAdjoinSave = new javax.swing.JButton();
        InversAdjoinPrompt = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        InversAdjoinInput = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        InversAdjoinIntermediate = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        InversAdjoinOutput = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 500));

        SidePanel.setBackground(new java.awt.Color(204, 204, 204));
        SidePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));

        SideHeader.setBackground(new java.awt.Color(153, 153, 153));

        HeaderLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeaderLabel.setText("Menu");
        HeaderLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout SideHeaderLayout = new javax.swing.GroupLayout(SideHeader);
        SideHeader.setLayout(SideHeaderLayout);
        SideHeaderLayout.setHorizontalGroup(
            SideHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
        );
        SideHeaderLayout.setVerticalGroup(
            SideHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        SideMenu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        SPLLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SPLLabel.setText("SPL");
        SideMenu.add(SPLLabel);

        Menu.add(SPLGauss);
        SPLGauss.setSelected(true);
        SPLGauss.setText("Metode Gauss");
        SPLGauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPLGaussActionPerformed(evt);
            }
        });
        SideMenu.add(SPLGauss);

        Menu.add(SPLGaussJordan);
        SPLGaussJordan.setText("Metode Gauss Jordan");
        SPLGaussJordan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPLGaussJordanActionPerformed(evt);
            }
        });
        SideMenu.add(SPLGaussJordan);

        Menu.add(SPLMatriksBalikan);
        SPLMatriksBalikan.setText("Metode Matriks Balikan");
        SideMenu.add(SPLMatriksBalikan);

        Menu.add(SPLCrammer);
        SPLCrammer.setText("Metode Crammer");
        SideMenu.add(SPLCrammer);

        DeterminanLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeterminanLabel.setText("Determinan");
        SideMenu.add(DeterminanLabel);

        Menu.add(DeterminanKofaktor);
        DeterminanKofaktor.setText("Ekspansi Kofaktor");
        DeterminanKofaktor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeterminanKofaktorActionPerformed(evt);
            }
        });
        SideMenu.add(DeterminanKofaktor);

        Menu.add(DeterminanOBE);
        DeterminanOBE.setText("Metode OBE");
        DeterminanOBE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeterminanOBEActionPerformed(evt);
            }
        });
        SideMenu.add(DeterminanOBE);

        InversLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InversLabel.setText("Invers");
        SideMenu.add(InversLabel);

        Menu.add(InversGauss);
        InversGauss.setText("Metode Gauss-Jordan");
        InversGauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InversGaussActionPerformed(evt);
            }
        });
        SideMenu.add(InversGauss);

        Menu.add(InversAdjoin);
        InversAdjoin.setText("Metode Adjoint");
        InversAdjoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InversAdjoinActionPerformed(evt);
            }
        });
        SideMenu.add(InversAdjoin);

        ProblemSolverLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ProblemSolverLabel.setText("Problem Solver");
        SideMenu.add(ProblemSolverLabel);

        Menu.add(Interpolasi);
        Interpolasi.setText("Interpolasi");
        SideMenu.add(Interpolasi);

        Menu.add(Regresi);
        Regresi.setText("Regresi");
        SideMenu.add(Regresi);

        ExitButton.setText("EXIT");
        ExitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        SideMenu.add(ExitButton);

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(SideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(SideHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addComponent(SideHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        LayeredPanel.setLayout(new java.awt.CardLayout());

        SPLGaussTitle.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        SPLGaussTitle.setText("SPL Metode Gauss");

        SPLGaussInst1.setText("Input Matriks Ax=b :");

        SPLGaussInst2.setText("Pisahkan elemen dengan spasi");

        SPLGaussInst3.setText("Pisahkan baris dengan newline (enter)");

        SPLGaussInst4.setText("Matriks eselon yang terbentuk");

        SPLGaussInst5.setText("Hasil:");

        SPLGaussInst6.setText("Tiap X dipisah newline");

        SPLGaussCalculate.setText("Calculate");
        SPLGaussCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPLGaussCalculateActionPerformed(evt);
            }
        });

        SPLGaussOpenFile.setText("Open");
        SPLGaussOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPLGaussOpenFileActionPerformed(evt);
            }
        });

        SPLGaussFilepath.setEditable(false);
        SPLGaussFilepath.setText("Open A File..");

        SPLGaussSave.setText("Save");
        SPLGaussSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPLGaussSaveActionPerformed(evt);
            }
        });

        SPLGaussPrompt.setText("Prompt");

        jScrollPane1.setViewportView(SPLGaussInput);

        SPLGaussIntermediate.setEditable(false);
        jScrollPane2.setViewportView(SPLGaussIntermediate);

        SPLGaussOutput.setEditable(false);
        jScrollPane3.setViewportView(SPLGaussOutput);

        javax.swing.GroupLayout SPLGaussPanelLayout = new javax.swing.GroupLayout(SPLGaussPanel);
        SPLGaussPanel.setLayout(SPLGaussPanelLayout);
        SPLGaussPanelLayout.setHorizontalGroup(
            SPLGaussPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SPLGaussPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(SPLGaussPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SPLGaussInst2, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addComponent(SPLGaussInst1)
                    .addComponent(SPLGaussInst3)
                    .addGroup(SPLGaussPanelLayout.createSequentialGroup()
                        .addGroup(SPLGaussPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SPLGaussInst4)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(SPLGaussPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SPLGaussInst5)
                            .addComponent(SPLGaussInst6)
                            .addComponent(SPLGaussCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SPLGaussPanelLayout.createSequentialGroup()
                                .addComponent(SPLGaussFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SPLGaussOpenFile))
                            .addComponent(SPLGaussSave, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SPLGaussPrompt)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56))
            .addGroup(SPLGaussPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SPLGaussTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SPLGaussPanelLayout.setVerticalGroup(
            SPLGaussPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SPLGaussPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SPLGaussTitle)
                .addGap(18, 18, 18)
                .addComponent(SPLGaussInst1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPLGaussInst2)
                .addGap(4, 4, 4)
                .addComponent(SPLGaussInst3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SPLGaussPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(SPLGaussPanelLayout.createSequentialGroup()
                        .addGroup(SPLGaussPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SPLGaussOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SPLGaussFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SPLGaussCalculate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SPLGaussSave)
                        .addGap(11, 11, 11)
                        .addComponent(SPLGaussPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SPLGaussPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SPLGaussInst4)
                    .addComponent(SPLGaussInst5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPLGaussInst6)
                .addGap(4, 4, 4)
                .addGroup(SPLGaussPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        LayeredPanel.add(SPLGaussPanel, "card2");

        SPLGaussTitle4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        SPLGaussTitle4.setText("SPL Metode Gauss Jordan");

        SPLGaussInst25.setText("Input Matriks Ax=b :");

        SPLGaussInst26.setText("Pisahkan elemen dengan spasi");

        SPLGaussInst27.setText("Pisahkan baris dengan newline (enter)");

        SPLGaussInst28.setText("Matriks eselon yang terbentuk");

        SPLGaussInst29.setText("Hasil:");

        SPLGaussInst30.setText("Tiap X dipisah newline");

        SPLGaussJordanCalculate.setText("Calculate");
        SPLGaussJordanCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPLGaussJordanCalculateActionPerformed(evt);
            }
        });

        SPLGaussJordanOpenFile.setText("Open");
        SPLGaussJordanOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPLGaussJordanOpenFileActionPerformed(evt);
            }
        });

        SPLGaussJordanFilepath.setEditable(false);
        SPLGaussJordanFilepath.setText("Open A File..");

        SPLGaussJordanSave.setText("Save");
        SPLGaussJordanSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPLGaussJordanSaveActionPerformed(evt);
            }
        });

        SPLGaussJordanPrompt.setText("Prompt");

        jScrollPane14.setViewportView(SPLGaussJordanInput);

        jScrollPane15.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        SPLGaussJordanIntermediate.setEditable(false);
        jScrollPane15.setViewportView(SPLGaussJordanIntermediate);

        SPLGaussJordanOutput.setEditable(false);
        jScrollPane16.setViewportView(SPLGaussJordanOutput);

        javax.swing.GroupLayout SPLGaussJordanPanelLayout = new javax.swing.GroupLayout(SPLGaussJordanPanel);
        SPLGaussJordanPanel.setLayout(SPLGaussJordanPanelLayout);
        SPLGaussJordanPanelLayout.setHorizontalGroup(
            SPLGaussJordanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SPLGaussJordanPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(SPLGaussJordanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SPLGaussInst26, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addComponent(SPLGaussInst25)
                    .addComponent(SPLGaussInst27)
                    .addGroup(SPLGaussJordanPanelLayout.createSequentialGroup()
                        .addGroup(SPLGaussJordanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SPLGaussInst28)
                            .addComponent(jScrollPane14)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(SPLGaussJordanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SPLGaussInst29)
                            .addComponent(SPLGaussInst30)
                            .addComponent(SPLGaussJordanCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SPLGaussJordanPanelLayout.createSequentialGroup()
                                .addComponent(SPLGaussJordanFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SPLGaussJordanOpenFile))
                            .addComponent(SPLGaussJordanSave, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SPLGaussJordanPrompt)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56))
            .addGroup(SPLGaussJordanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SPLGaussTitle4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SPLGaussJordanPanelLayout.setVerticalGroup(
            SPLGaussJordanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SPLGaussJordanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SPLGaussTitle4)
                .addGap(18, 18, 18)
                .addComponent(SPLGaussInst25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPLGaussInst26)
                .addGap(4, 4, 4)
                .addComponent(SPLGaussInst27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SPLGaussJordanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(SPLGaussJordanPanelLayout.createSequentialGroup()
                        .addGroup(SPLGaussJordanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SPLGaussJordanOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SPLGaussJordanFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SPLGaussJordanCalculate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SPLGaussJordanSave)
                        .addGap(11, 11, 11)
                        .addComponent(SPLGaussJordanPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SPLGaussJordanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SPLGaussInst28)
                    .addComponent(SPLGaussInst29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPLGaussInst30)
                .addGap(4, 4, 4)
                .addGroup(SPLGaussJordanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane15)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        LayeredPanel.add(SPLGaussJordanPanel, "card2");

        DeterminanKofaktorTitle.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        DeterminanKofaktorTitle.setText("Determinan Metode Ekspansi Kofaktor");

        SPLGaussInst7.setText("Input Matriks Ax=b :");

        SPLGaussInst8.setText("Pisahkan elemen dengan spasi");

        SPLGaussInst9.setText("Pisahkan baris dengan newline (enter)");

        SPLGaussInst11.setText("Hasil:");

        DeterminanKofaktorCalculate.setText("Calculate");
        DeterminanKofaktorCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeterminanKofaktorCalculateActionPerformed(evt);
            }
        });

        DeterminanKofaktorOpenFile.setText("Open");
        DeterminanKofaktorOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeterminanKofaktorOpenFileActionPerformed(evt);
            }
        });

        DeterminanKofaktorFilepath.setEditable(false);
        DeterminanKofaktorFilepath.setText("Open A File..");

        DeterminanKofaktorSave.setText("Save");
        DeterminanKofaktorSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeterminanKofaktorSaveActionPerformed(evt);
            }
        });

        DeterminanKofaktorPrompt.setText("Prompt");

        jScrollPane4.setViewportView(DeterminanKofaktorInput);

        DeterminanKofaktorOutput.setEditable(false);
        jScrollPane6.setViewportView(DeterminanKofaktorOutput);

        javax.swing.GroupLayout DeterminanKofaktorPanelLayout = new javax.swing.GroupLayout(DeterminanKofaktorPanel);
        DeterminanKofaktorPanel.setLayout(DeterminanKofaktorPanelLayout);
        DeterminanKofaktorPanelLayout.setHorizontalGroup(
            DeterminanKofaktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeterminanKofaktorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DeterminanKofaktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeterminanKofaktorTitle)
                    .addGroup(DeterminanKofaktorPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(DeterminanKofaktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SPLGaussInst7)
                            .addComponent(SPLGaussInst9)
                            .addGroup(DeterminanKofaktorPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(DeterminanKofaktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SPLGaussInst11)
                                    .addComponent(DeterminanKofaktorCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(DeterminanKofaktorPanelLayout.createSequentialGroup()
                                        .addComponent(DeterminanKofaktorFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DeterminanKofaktorOpenFile))
                                    .addComponent(DeterminanKofaktorSave, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DeterminanKofaktorPrompt)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(SPLGaussInst8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        DeterminanKofaktorPanelLayout.setVerticalGroup(
            DeterminanKofaktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeterminanKofaktorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DeterminanKofaktorTitle)
                .addGap(18, 18, 18)
                .addComponent(SPLGaussInst7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPLGaussInst8)
                .addGap(4, 4, 4)
                .addComponent(SPLGaussInst9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DeterminanKofaktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DeterminanKofaktorPanelLayout.createSequentialGroup()
                        .addGroup(DeterminanKofaktorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeterminanKofaktorOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeterminanKofaktorFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DeterminanKofaktorCalculate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DeterminanKofaktorSave)
                        .addGap(11, 11, 11)
                        .addComponent(DeterminanKofaktorPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SPLGaussInst11)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        LayeredPanel.add(DeterminanKofaktorPanel, "card2");

        SPLGaussTitle1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        SPLGaussTitle1.setText("Determinan Metode OBE");

        SPLGaussInst10.setText("Input Matriks Ax=b :");

        SPLGaussInst12.setText("Pisahkan elemen dengan spasi");

        SPLGaussInst13.setText("Pisahkan baris dengan newline (enter)");

        SPLGaussInst14.setText("Matriks eselon yang terbentuk");

        SPLGaussInst15.setText("Hasil:");

        DeterminanOBECalculate.setText("Calculate");
        DeterminanOBECalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeterminanOBECalculateActionPerformed(evt);
            }
        });

        DeterminanOBEOpenFile.setText("Open");
        DeterminanOBEOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeterminanOBEOpenFileActionPerformed(evt);
            }
        });

        DeterminanOBEFilepath.setEditable(false);
        DeterminanOBEFilepath.setText("Open A File..");

        DeterminanOBESave.setText("Save");
        DeterminanOBESave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeterminanOBESaveActionPerformed(evt);
            }
        });

        DeterminanOBEPrompt.setText("Prompt");

        jScrollPane5.setViewportView(DeterminanOBEInput);

        DeterminanOBEIntermediate.setEditable(false);
        jScrollPane7.setViewportView(DeterminanOBEIntermediate);

        DeterminanOBEOutput.setEditable(false);
        jScrollPane8.setViewportView(DeterminanOBEOutput);

        javax.swing.GroupLayout DeterminanOBEPanelLayout = new javax.swing.GroupLayout(DeterminanOBEPanel);
        DeterminanOBEPanel.setLayout(DeterminanOBEPanelLayout);
        DeterminanOBEPanelLayout.setHorizontalGroup(
            DeterminanOBEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeterminanOBEPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DeterminanOBEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SPLGaussTitle1)
                    .addGroup(DeterminanOBEPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(DeterminanOBEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SPLGaussInst10)
                            .addComponent(SPLGaussInst13)
                            .addGroup(DeterminanOBEPanelLayout.createSequentialGroup()
                                .addGroup(DeterminanOBEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SPLGaussInst14)
                                    .addComponent(jScrollPane5)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(DeterminanOBEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SPLGaussInst15)
                                    .addComponent(DeterminanOBECalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(DeterminanOBEPanelLayout.createSequentialGroup()
                                        .addComponent(DeterminanOBEFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DeterminanOBEOpenFile))
                                    .addComponent(DeterminanOBESave, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DeterminanOBEPrompt)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(SPLGaussInst12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        DeterminanOBEPanelLayout.setVerticalGroup(
            DeterminanOBEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeterminanOBEPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SPLGaussTitle1)
                .addGap(18, 18, 18)
                .addComponent(SPLGaussInst10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPLGaussInst12)
                .addGap(4, 4, 4)
                .addComponent(SPLGaussInst13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DeterminanOBEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DeterminanOBEPanelLayout.createSequentialGroup()
                        .addGroup(DeterminanOBEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeterminanOBEOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeterminanOBEFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DeterminanOBECalculate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DeterminanOBESave)
                        .addGap(11, 11, 11)
                        .addComponent(DeterminanOBEPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DeterminanOBEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SPLGaussInst14)
                    .addComponent(SPLGaussInst15))
                .addGap(24, 24, 24)
                .addGroup(DeterminanOBEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        LayeredPanel.add(DeterminanOBEPanel, "card2");

        SPLGaussTitle2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        SPLGaussTitle2.setText("Invers Metode Gauss Jordan");

        SPLGaussInst16.setText("Input Matriks Ax=b :");

        SPLGaussInst17.setText("Pisahkan elemen dengan spasi");

        SPLGaussInst18.setText("Pisahkan baris dengan newline (enter)");

        SPLGaussInst20.setText("Hasil:");

        InversGaussCalculate.setText("Calculate");
        InversGaussCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InversGaussCalculateActionPerformed(evt);
            }
        });

        InversGaussOpenFile.setText("Open");
        InversGaussOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InversGaussOpenFileActionPerformed(evt);
            }
        });

        InversGaussFilepath.setEditable(false);
        InversGaussFilepath.setText("Open A File..");

        InversGaussSave.setText("Save");

        InversGaussPrompt.setText("Prompt");

        jScrollPane9.setViewportView(InversGaussInput);

        InversGaussOutput.setEditable(false);
        jScrollPane11.setViewportView(InversGaussOutput);

        javax.swing.GroupLayout InversGaussPanelLayout = new javax.swing.GroupLayout(InversGaussPanel);
        InversGaussPanel.setLayout(InversGaussPanelLayout);
        InversGaussPanelLayout.setHorizontalGroup(
            InversGaussPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InversGaussPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InversGaussPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SPLGaussTitle2)
                    .addGroup(InversGaussPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(InversGaussPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SPLGaussInst16)
                            .addComponent(SPLGaussInst18)
                            .addGroup(InversGaussPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(InversGaussPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SPLGaussInst20)
                                    .addComponent(InversGaussCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(InversGaussPanelLayout.createSequentialGroup()
                                        .addComponent(InversGaussFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(InversGaussOpenFile))
                                    .addComponent(InversGaussSave, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InversGaussPrompt)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(SPLGaussInst17, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        InversGaussPanelLayout.setVerticalGroup(
            InversGaussPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InversGaussPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SPLGaussTitle2)
                .addGap(18, 18, 18)
                .addComponent(SPLGaussInst16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPLGaussInst17)
                .addGap(4, 4, 4)
                .addComponent(SPLGaussInst18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InversGaussPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(InversGaussPanelLayout.createSequentialGroup()
                        .addGroup(InversGaussPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InversGaussOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InversGaussFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InversGaussCalculate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InversGaussSave)
                        .addGap(11, 11, 11)
                        .addComponent(InversGaussPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SPLGaussInst20)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        LayeredPanel.add(InversGaussPanel, "card2");

        SPLGaussTitle3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        SPLGaussTitle3.setText("Invers Metode Adjoin");

        SPLGaussInst19.setText("Input Matriks Ax=b :");

        SPLGaussInst21.setText("Pisahkan elemen dengan spasi");

        SPLGaussInst22.setText("Pisahkan baris dengan newline (enter)");

        SPLGaussInst23.setText("Matriks Kofaktor yang terbentuk");

        SPLGaussInst24.setText("Hasil:");

        InversAdjoinCalculate.setText("Calculate");
        InversAdjoinCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InversAdjoinCalculateActionPerformed(evt);
            }
        });

        InversAdjoinOpenFile.setText("Open");
        InversAdjoinOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InversAdjoinOpenFileActionPerformed(evt);
            }
        });

        InversAdjoinFilepath.setEditable(false);
        InversAdjoinFilepath.setText("Open A File..");

        InversAdjoinSave.setText("Save");

        InversAdjoinPrompt.setText("Prompt");

        jScrollPane10.setViewportView(InversAdjoinInput);

        InversAdjoinIntermediate.setEditable(false);
        jScrollPane12.setViewportView(InversAdjoinIntermediate);

        InversAdjoinOutput.setEditable(false);
        jScrollPane13.setViewportView(InversAdjoinOutput);

        javax.swing.GroupLayout InversAdjoinPanelLayout = new javax.swing.GroupLayout(InversAdjoinPanel);
        InversAdjoinPanel.setLayout(InversAdjoinPanelLayout);
        InversAdjoinPanelLayout.setHorizontalGroup(
            InversAdjoinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InversAdjoinPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InversAdjoinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SPLGaussTitle3)
                    .addGroup(InversAdjoinPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(InversAdjoinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InversAdjoinPanelLayout.createSequentialGroup()
                                .addGroup(InversAdjoinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(InversAdjoinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane10)
                                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(SPLGaussInst23, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(InversAdjoinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(InversAdjoinCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(InversAdjoinPanelLayout.createSequentialGroup()
                                        .addComponent(InversAdjoinFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(InversAdjoinOpenFile))
                                    .addComponent(InversAdjoinSave, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane13)
                                    .addComponent(SPLGaussInst24, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InversAdjoinPrompt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(InversAdjoinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(SPLGaussInst22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                .addComponent(SPLGaussInst21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SPLGaussInst19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        InversAdjoinPanelLayout.setVerticalGroup(
            InversAdjoinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InversAdjoinPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SPLGaussTitle3)
                .addGap(18, 18, 18)
                .addComponent(SPLGaussInst19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPLGaussInst21)
                .addGap(4, 4, 4)
                .addComponent(SPLGaussInst22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InversAdjoinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(InversAdjoinPanelLayout.createSequentialGroup()
                        .addGroup(InversAdjoinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InversAdjoinOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InversAdjoinFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InversAdjoinCalculate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InversAdjoinSave)
                        .addGap(11, 11, 11)
                        .addComponent(InversAdjoinPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InversAdjoinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SPLGaussInst23)
                    .addComponent(SPLGaussInst24))
                .addGap(24, 24, 24)
                .addGroup(InversAdjoinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane12)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        LayeredPanel.add(InversAdjoinPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(LayeredPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(LayeredPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SPLGaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPLGaussActionPerformed
        if (SPLGauss.isSelected()) {
            LayeredPanel.removeAll();
            LayeredPanel.add(SPLGaussPanel);
            LayeredPanel.repaint();
            LayeredPanel.revalidate();
        }
    }//GEN-LAST:event_SPLGaussActionPerformed

    private void SPLGaussJordanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPLGaussJordanActionPerformed
        if (SPLGaussJordan.isSelected()) {
            LayeredPanel.removeAll();
            LayeredPanel.add(SPLGaussJordanPanel);
            LayeredPanel.repaint();
            LayeredPanel.revalidate();
        }
    }//GEN-LAST:event_SPLGaussJordanActionPerformed

    private void SPLGaussOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPLGaussOpenFileActionPerformed
        int result = FileOpener.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = FileOpener.getSelectedFile();
            SPLGaussFilepath.setText(selectedFile.getAbsolutePath());
            SPLGaussInput.setText(Parser.fileToMatrix(selectedFile).toString());
        }
    }//GEN-LAST:event_SPLGaussOpenFileActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void DeterminanKofaktorOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeterminanKofaktorOpenFileActionPerformed
        int result = FileOpener.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = FileOpener.getSelectedFile();
            DeterminanKofaktorFilepath.setText(selectedFile.getAbsolutePath());
            DeterminanKofaktorInput.setText(Parser.fileToMatrix(selectedFile).toString());
        }
    }//GEN-LAST:event_DeterminanKofaktorOpenFileActionPerformed

    private void DeterminanKofaktorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeterminanKofaktorActionPerformed
        if (DeterminanKofaktor.isSelected()) {
            LayeredPanel.removeAll();
            LayeredPanel.add(DeterminanKofaktorPanel);
            LayeredPanel.repaint();
            LayeredPanel.revalidate();
        }
    }//GEN-LAST:event_DeterminanKofaktorActionPerformed

    private void SPLGaussCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPLGaussCalculateActionPerformed
        try {
            Matrix M = Parser.stringToMatrix(SPLGaussInput.getText());
            M.toEchelonForm(false);
            SPLGaussIntermediate.setText(M.toString());
            SolutionResult res = SPLSolver.backwardSubstitution(M);
            SPLGaussOutput.setText(res.toString());
        } catch (Exception e) {
            SPLGaussPrompt.setText("Input tidak valid");
        }
    }//GEN-LAST:event_SPLGaussCalculateActionPerformed

    private void DeterminanKofaktorCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeterminanKofaktorCalculateActionPerformed
        try {
            Matrix M = Parser.stringToMatrix(DeterminanKofaktorInput.getText());
            if (M.isSquare()) {
                double output = DeterminantSolver.CofactorExpansion(M);
                DeterminanKofaktorOutput.setText(String.format(Locale.ROOT, "%.2f", (double) Math.round(100 * output) / 100));
            } else {
                DeterminanKofaktorPrompt.setText("Matriks tidak persegi");
            }
        } catch (Exception e) {
            DeterminanKofaktorPrompt.setText("Input tidak valid");
        }
    }//GEN-LAST:event_DeterminanKofaktorCalculateActionPerformed

    private void DeterminanOBECalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeterminanOBECalculateActionPerformed
        try {
            Matrix M = Parser.stringToMatrix(DeterminanOBEInput.getText());
            if (M.isSquare()) {
                Matrix res = new Matrix(M.getNRow(), M.getNCol());
                double output = DeterminantSolver.ERO(M, res);
                DeterminanOBEOutput.setText(String.format(Locale.ROOT, "%.2f", (double) Math.round(100 * output) / 100));
                DeterminanOBEIntermediate.setText(res.toString());
            } else {
                DeterminanOBEPrompt.setText("Matriks tidak persegi");
            }
        } catch (Exception e) {
            DeterminanOBEPrompt.setText("Input tidak valid");
        }
    }//GEN-LAST:event_DeterminanOBECalculateActionPerformed

    private void DeterminanOBEOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeterminanOBEOpenFileActionPerformed
        int result = FileOpener.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = FileOpener.getSelectedFile();
            DeterminanOBEFilepath.setText(selectedFile.getAbsolutePath());
            DeterminanOBEInput.setText(Parser.fileToMatrix(selectedFile).toString());
        }
    }//GEN-LAST:event_DeterminanOBEOpenFileActionPerformed

    private void DeterminanOBEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeterminanOBEActionPerformed
        if (DeterminanOBE.isSelected()) {
            LayeredPanel.removeAll();
            LayeredPanel.add(DeterminanOBEPanel);
            LayeredPanel.repaint();
            LayeredPanel.revalidate();
        }
    }//GEN-LAST:event_DeterminanOBEActionPerformed

    private void InversGaussCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InversGaussCalculateActionPerformed
        try {
            Matrix M = Parser.stringToMatrix(InversGaussInput.getText());
            if (M.isSquare()) {
                Matrix output = InversSolver.GaussJordanMethod(M);
                if (output != null) {
                    InversGaussOutput.setText(output.toString());
                } else {
                    InversGaussOutput.setText("Invers tidak ditemukan.");
                }
            } else {
                InversGaussPrompt.setText("Matriks tidak persegi");
            }
        } catch (Exception e) {
            InversGaussPrompt.setText("Input tidak valid");
        }
    }//GEN-LAST:event_InversGaussCalculateActionPerformed

    private void InversGaussOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InversGaussOpenFileActionPerformed
        int result = FileOpener.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = FileOpener.getSelectedFile();
            InversGaussFilepath.setText(selectedFile.getAbsolutePath());
            InversGaussInput.setText(Parser.fileToMatrix(selectedFile).toString());
        }
    }//GEN-LAST:event_InversGaussOpenFileActionPerformed

    private void InversGaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InversGaussActionPerformed
        if (InversGauss.isSelected()) {
            LayeredPanel.removeAll();
            LayeredPanel.add(InversGaussPanel);
            LayeredPanel.repaint();
            LayeredPanel.revalidate();
        }
    }//GEN-LAST:event_InversGaussActionPerformed

    private void InversAdjoinCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InversAdjoinCalculateActionPerformed
        try {
            Matrix M = Parser.stringToMatrix(InversAdjoinInput.getText());
            if (M.isSquare()) {
                Matrix output = InversSolver.AdjointMethod(M);
                if (output != null) {
                    InversAdjoinOutput.setText(output.toString());
                } else {
                    InversAdjoinOutput.setText("Invers tidak ditemukan.");
                }
            } else {
                InversAdjoinPrompt.setText("Matriks tidak persegi");
            }
        } catch (Exception e) {
            InversAdjoinPrompt.setText("Input tidak valid");
        }
    }//GEN-LAST:event_InversAdjoinCalculateActionPerformed

    private void InversAdjoinOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InversAdjoinOpenFileActionPerformed
        int result = FileOpener.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = FileOpener.getSelectedFile();
            InversAdjoinFilepath.setText(selectedFile.getAbsolutePath());
            InversAdjoinInput.setText(Parser.fileToMatrix(selectedFile).toString());
        }
    }//GEN-LAST:event_InversAdjoinOpenFileActionPerformed

    private void SPLGaussSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPLGaussSaveActionPerformed
        if (SPLGaussOutput.getText().equals("")) {
            SPLGaussPrompt.setText("Output kosong, silahkan lakukan kalkukasi");
        } else {
            int result = FileSaver.showSaveDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                Parser.stringToFile(SPLGaussOutput.getText(), FileSaver.getSelectedFile().toString() + ".txt");
                SPLGaussPrompt.setText("File berhasil di-save");
            }
        }
    }//GEN-LAST:event_SPLGaussSaveActionPerformed

    private void SPLGaussJordanCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPLGaussJordanCalculateActionPerformed
        try {
            Matrix M = Parser.stringToMatrix(SPLGaussJordanInput.getText());
            M.toEchelonForm(true);
            SPLGaussJordanIntermediate.setText(M.toString());
            SolutionResult res = SPLSolver.backwardSubstitution(M);
            SPLGaussJordanOutput.setText(res.toString());
        } catch (Exception e) {
            SPLGaussJordanPrompt.setText("Input tidak valid");
        }
    }//GEN-LAST:event_SPLGaussJordanCalculateActionPerformed

    private void SPLGaussJordanOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPLGaussJordanOpenFileActionPerformed
        int result = FileOpener.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = FileOpener.getSelectedFile();
            SPLGaussJordanFilepath.setText(selectedFile.getAbsolutePath());
            SPLGaussJordanInput.setText(Parser.fileToMatrix(selectedFile).toString());
        }
    }//GEN-LAST:event_SPLGaussJordanOpenFileActionPerformed

    private void SPLGaussJordanSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPLGaussJordanSaveActionPerformed
        if (SPLGaussJordanOutput.getText().equals("")) {
            SPLGaussJordanPrompt.setText("Output kosong, silahkan lakukan kalkukasi");
        } else {
            int result = FileSaver.showSaveDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                Parser.stringToFile(SPLGaussJordanOutput.getText(), FileSaver.getSelectedFile().toString() + ".txt");
                SPLGaussJordanPrompt.setText("File berhasil di-save");
            }
        }
    }//GEN-LAST:event_SPLGaussJordanSaveActionPerformed

    private void DeterminanKofaktorSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeterminanKofaktorSaveActionPerformed
        if (DeterminanKofaktorOutput.getText().equals("")) {
            DeterminanKofaktorPrompt.setText("Output kosong, silahkan lakukan kalkukasi");
        } else {
            int result = FileSaver.showSaveDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                Parser.stringToFile(DeterminanKofaktorOutput.getText(), FileSaver.getSelectedFile().toString() + ".txt");
                DeterminanKofaktorPrompt.setText("File berhasil di-save");
            }
        }
    }//GEN-LAST:event_DeterminanKofaktorSaveActionPerformed

    private void DeterminanOBESaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeterminanOBESaveActionPerformed
        if (DeterminanOBEOutput.getText().equals("")) {
            DeterminanOBEPrompt.setText("Output kosong, silahkan lakukan kalkukasi");
        } else {
            int result = FileSaver.showSaveDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                Parser.stringToFile(DeterminanOBEOutput.getText(), FileSaver.getSelectedFile().toString() + ".txt");
                DeterminanOBEPrompt.setText("File berhasil di-save");
            }
        }
    }//GEN-LAST:event_DeterminanOBESaveActionPerformed

    private void InversAdjoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InversAdjoinActionPerformed
        if (InversAdjoin.isSelected()) {
            LayeredPanel.removeAll();
            LayeredPanel.add(InversAdjoinPanel);
            LayeredPanel.repaint();
            LayeredPanel.revalidate();
        }
    }//GEN-LAST:event_InversAdjoinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DeterminanKofaktor;
    private javax.swing.JButton DeterminanKofaktorCalculate;
    private javax.swing.JTextField DeterminanKofaktorFilepath;
    private javax.swing.JTextPane DeterminanKofaktorInput;
    private javax.swing.JButton DeterminanKofaktorOpenFile;
    private javax.swing.JTextPane DeterminanKofaktorOutput;
    private javax.swing.JPanel DeterminanKofaktorPanel;
    private javax.swing.JLabel DeterminanKofaktorPrompt;
    private javax.swing.JButton DeterminanKofaktorSave;
    private javax.swing.JLabel DeterminanKofaktorTitle;
    private javax.swing.JLabel DeterminanLabel;
    private javax.swing.JRadioButton DeterminanOBE;
    private javax.swing.JButton DeterminanOBECalculate;
    private javax.swing.JTextField DeterminanOBEFilepath;
    private javax.swing.JTextPane DeterminanOBEInput;
    private javax.swing.JTextPane DeterminanOBEIntermediate;
    private javax.swing.JButton DeterminanOBEOpenFile;
    private javax.swing.JTextPane DeterminanOBEOutput;
    private javax.swing.JPanel DeterminanOBEPanel;
    private javax.swing.JLabel DeterminanOBEPrompt;
    private javax.swing.JButton DeterminanOBESave;
    private javax.swing.JButton ExitButton;
    private javax.swing.JFileChooser FileOpener;
    private javax.swing.JFileChooser FileSaver;
    private javax.swing.JLabel HeaderLabel;
    private javax.swing.JRadioButton Interpolasi;
    private javax.swing.JRadioButton InversAdjoin;
    private javax.swing.JButton InversAdjoinCalculate;
    private javax.swing.JTextField InversAdjoinFilepath;
    private javax.swing.JTextPane InversAdjoinInput;
    private javax.swing.JTextPane InversAdjoinIntermediate;
    private javax.swing.JButton InversAdjoinOpenFile;
    private javax.swing.JTextPane InversAdjoinOutput;
    private javax.swing.JPanel InversAdjoinPanel;
    private javax.swing.JLabel InversAdjoinPrompt;
    private javax.swing.JButton InversAdjoinSave;
    private javax.swing.JRadioButton InversGauss;
    private javax.swing.JButton InversGaussCalculate;
    private javax.swing.JTextField InversGaussFilepath;
    private javax.swing.JTextPane InversGaussInput;
    private javax.swing.JButton InversGaussOpenFile;
    private javax.swing.JTextPane InversGaussOutput;
    private javax.swing.JPanel InversGaussPanel;
    private javax.swing.JLabel InversGaussPrompt;
    private javax.swing.JButton InversGaussSave;
    private javax.swing.JLabel InversLabel;
    private javax.swing.JLayeredPane LayeredPanel;
    private javax.swing.ButtonGroup Menu;
    private javax.swing.JLabel ProblemSolverLabel;
    private javax.swing.JRadioButton Regresi;
    private javax.swing.JRadioButton SPLCrammer;
    private javax.swing.JRadioButton SPLGauss;
    private javax.swing.JButton SPLGaussCalculate;
    private javax.swing.JTextField SPLGaussFilepath;
    private javax.swing.JTextPane SPLGaussInput;
    private javax.swing.JLabel SPLGaussInst1;
    private javax.swing.JLabel SPLGaussInst10;
    private javax.swing.JLabel SPLGaussInst11;
    private javax.swing.JLabel SPLGaussInst12;
    private javax.swing.JLabel SPLGaussInst13;
    private javax.swing.JLabel SPLGaussInst14;
    private javax.swing.JLabel SPLGaussInst15;
    private javax.swing.JLabel SPLGaussInst16;
    private javax.swing.JLabel SPLGaussInst17;
    private javax.swing.JLabel SPLGaussInst18;
    private javax.swing.JLabel SPLGaussInst19;
    private javax.swing.JLabel SPLGaussInst2;
    private javax.swing.JLabel SPLGaussInst20;
    private javax.swing.JLabel SPLGaussInst21;
    private javax.swing.JLabel SPLGaussInst22;
    private javax.swing.JLabel SPLGaussInst23;
    private javax.swing.JLabel SPLGaussInst24;
    private javax.swing.JLabel SPLGaussInst25;
    private javax.swing.JLabel SPLGaussInst26;
    private javax.swing.JLabel SPLGaussInst27;
    private javax.swing.JLabel SPLGaussInst28;
    private javax.swing.JLabel SPLGaussInst29;
    private javax.swing.JLabel SPLGaussInst3;
    private javax.swing.JLabel SPLGaussInst30;
    private javax.swing.JLabel SPLGaussInst4;
    private javax.swing.JLabel SPLGaussInst5;
    private javax.swing.JLabel SPLGaussInst6;
    private javax.swing.JLabel SPLGaussInst7;
    private javax.swing.JLabel SPLGaussInst8;
    private javax.swing.JLabel SPLGaussInst9;
    private javax.swing.JTextPane SPLGaussIntermediate;
    private javax.swing.JRadioButton SPLGaussJordan;
    private javax.swing.JButton SPLGaussJordanCalculate;
    private javax.swing.JTextField SPLGaussJordanFilepath;
    private javax.swing.JTextPane SPLGaussJordanInput;
    private javax.swing.JTextPane SPLGaussJordanIntermediate;
    private javax.swing.JButton SPLGaussJordanOpenFile;
    private javax.swing.JTextPane SPLGaussJordanOutput;
    private javax.swing.JPanel SPLGaussJordanPanel;
    private javax.swing.JLabel SPLGaussJordanPrompt;
    private javax.swing.JButton SPLGaussJordanSave;
    private javax.swing.JButton SPLGaussOpenFile;
    private javax.swing.JTextPane SPLGaussOutput;
    private javax.swing.JPanel SPLGaussPanel;
    private javax.swing.JLabel SPLGaussPrompt;
    private javax.swing.JButton SPLGaussSave;
    private javax.swing.JLabel SPLGaussTitle;
    private javax.swing.JLabel SPLGaussTitle1;
    private javax.swing.JLabel SPLGaussTitle2;
    private javax.swing.JLabel SPLGaussTitle3;
    private javax.swing.JLabel SPLGaussTitle4;
    private javax.swing.JLabel SPLLabel;
    private javax.swing.JRadioButton SPLMatriksBalikan;
    private javax.swing.JPanel SideHeader;
    private javax.swing.JPanel SideMenu;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables
}
