name: Build and Coverage

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Prep
      run: |
        mkdir /tmp/build-artifact
        cd /tmp/build-artifact
        git init
        git remote add origin https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
        cache: maven
        
    - name: Build
      run: mvn install
    
    - name: Coverage Report
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: bin/site/jacoco
      
    - name: Commit and Push
      run: |
        cp -r . /tmp/build-artifact
        cd /tmp/build-artifact
        rm .gitignore
        mv .gitignore-build .gitignore
        git checkout -b build
        git add .gitignore
        git add .
        git config user.name "GitHub"
        git config user.email "noreply@github.com"
        git commit --allow-empty --author "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -m "Create nightly build $(git rev-parse --short "$GITHUB_SHA")"
        git push -u origin build -f
